import type { Doc } from './types';

// ─────────────────────────────────────────────────────────────
// Sift's corpus — a curated knowledge base of software-engineering
// concepts. Each entry is one document; the seed script embeds the
// title + content and loads it into Postgres.
// ─────────────────────────────────────────────────────────────

export const CATEGORIES = [
  'Databases',
  'Distributed Systems',
  'Web',
  'Machine Learning',
  'Security',
  'Systems',
] as const;

// [id, title, content, category, tags, year]
type Row = [string, string, string, string, string[], number];

const ROWS: Row[] = [
  // ── Databases ────────────────────────────────────────────
  ['db-hnsw', 'HNSW vector indexes',
    'Hierarchical Navigable Small World graphs index high-dimensional vectors as a layered proximity graph. Search descends from a sparse top layer to dense lower layers, giving logarithmic-time approximate nearest-neighbour lookups. The ef_search parameter trades recall against latency at query time.',
    'Databases', ['vectors', 'indexing', 'ann', 'pgvector'], 2024],
  ['db-ivfflat', 'IVFFlat vector indexes',
    'IVFFlat partitions vectors into lists around centroids found by k-means. A query probes only the nearest few lists, so it scans a fraction of the data. It builds faster and smaller than HNSW but needs the data present before indexing and gives lower recall at the same speed.',
    'Databases', ['vectors', 'indexing', 'ann'], 2023],
  ['db-pgvector', 'pgvector',
    'pgvector adds vector similarity search to Postgres with vector, halfvec, bit and sparsevec types and HNSW and IVFFlat indexes. It supports cosine, L2 and inner-product distance, so embeddings can live beside relational data and be filtered with ordinary SQL.',
    'Databases', ['pgvector', 'postgres', 'vectors'], 2024],
  ['db-mvcc', 'Multi-version concurrency control',
    'MVCC lets readers and writers avoid blocking each other by keeping multiple versions of each row. Every transaction sees a consistent snapshot taken at its start. Postgres implements this with per-row xmin/xmax visibility, and VACUUM later reclaims the dead tuples.',
    'Databases', ['transactions', 'concurrency', 'postgres'], 2021],
  ['db-btree', 'B-tree indexes',
    'The B-tree is the default index for ordered data. Its balanced, high-fan-out structure keeps lookups, range scans and ordered retrieval at logarithmic cost. Most equality and comparison queries are served by a B-tree unless the planner judges a sequential scan cheaper.',
    'Databases', ['indexing', 'postgres'], 2019],
  ['db-wal', 'Write-ahead logging',
    'Write-ahead logging records every change to a durable log before the change touches the data files. On crash recovery the log is replayed to restore a consistent state. The same stream of WAL records also drives streaming replication to standby servers.',
    'Databases', ['durability', 'recovery', 'replication'], 2020],
  ['db-isolation', 'Transaction isolation levels',
    'Isolation levels define which concurrency anomalies a transaction may observe — dirty reads, non-repeatable reads, phantoms. SQL defines read committed, repeatable read and serializable. Stronger isolation is simpler to reason about but costs throughput under contention.',
    'Databases', ['transactions', 'concurrency'], 2018],
  ['db-sharding', 'Database sharding',
    'Sharding splits one logical dataset across many database instances by a shard key, so writes and storage scale horizontally. The cost is that cross-shard queries, joins and transactions become hard, and rebalancing a poorly chosen shard key is painful.',
    'Databases', ['scaling', 'partitioning'], 2022],
  ['db-replication', 'Replication and read replicas',
    'Replication copies a primary database to one or more standbys. Read replicas absorb read traffic and provide failover targets. Asynchronous replication risks losing recent writes on failover; synchronous replication avoids that but adds commit latency.',
    'Databases', ['replication', 'scaling', 'availability'], 2021],
  ['db-fts', 'Full-text search in Postgres',
    'Postgres full-text search converts documents to a tsvector of normalised lexemes and matches them against a tsquery. A GIN index makes lookups fast, ts_rank scores relevance, and websearch_to_tsquery parses natural query strings into boolean term expressions.',
    'Databases', ['search', 'postgres', 'text'], 2023],
  ['db-rrf', 'Reciprocal Rank Fusion',
    'Reciprocal Rank Fusion merges several ranked lists without tuning score scales. Each result scores the sum of 1/(k + rank) across the lists it appears in, with k around 60. It is the standard way to fuse vector and keyword search into one hybrid ranking.',
    'Databases', ['search', 'ranking', 'hybrid'], 2024],
  ['db-connection-pool', 'Connection pooling',
    'Each Postgres connection is a backend process, so opening one per request is expensive and caps concurrency. A pooler such as PgBouncer keeps a small set of warm connections and multiplexes clients onto them — essential for serverless, where functions scale out fast.',
    'Databases', ['scaling', 'postgres', 'serverless'], 2022],
  ['db-query-planner', 'The query planner',
    'The planner turns SQL into an execution plan by estimating the cost of alternatives — index scan versus sequential scan, join orders, join algorithms. Estimates come from table statistics, so stale statistics are a common cause of a planner choosing a slow plan.',
    'Databases', ['performance', 'postgres', 'explain'], 2020],
  ['db-quantization', 'Vector quantization',
    'Quantization shrinks embeddings by storing them at lower precision. Scalar quantization to int8, or pgvector\'s halfvec, roughly halves storage and index size with little recall loss; binary quantization is far smaller and is paired with a rerank pass to recover accuracy.',
    'Databases', ['vectors', 'compression', 'pgvector'], 2024],

  // ── Distributed Systems ──────────────────────────────────
  ['ds-cap', 'The CAP theorem',
    'The CAP theorem says that when a network partition occurs, a distributed system must choose between consistency and availability. The interesting decision is the partition behaviour; in normal operation systems tune the latency-versus-consistency trade rather than abandoning either.',
    'Distributed Systems', ['theory', 'consistency', 'availability'], 2018],
  ['ds-consensus', 'Consensus and Raft',
    'Consensus lets a set of nodes agree on an ordered log of operations despite failures. Raft makes this understandable by electing a leader that appends entries and replicates them; an entry commits once a majority has stored it.',
    'Distributed Systems', ['consensus', 'raft', 'replication'], 2020],
  ['ds-consistent-hash', 'Consistent hashing',
    'Consistent hashing maps both keys and nodes onto a ring so that adding or removing a node moves only a small fraction of keys. Virtual nodes even out the load. It underpins distributed caches and partitioned datastores.',
    'Distributed Systems', ['partitioning', 'hashing', 'scaling'], 2019],
  ['ds-idempotency', 'Idempotency',
    'An idempotent operation can be retried safely because repeating it has no extra effect. Clients send an idempotency key; the server records the first result against that key and returns it for any retry. It is the foundation of safe retries in unreliable networks.',
    'Distributed Systems', ['reliability', 'retries', 'api'], 2022],
  ['ds-backpressure', 'Backpressure',
    'Backpressure is how a system signals that it cannot accept work as fast as it arrives. Bounded queues, flow control and load shedding stop a fast producer from exhausting a slow consumer\'s memory and turning a slowdown into a cascading failure.',
    'Distributed Systems', ['reliability', 'flow-control'], 2021],
  ['ds-eventual', 'Eventual consistency',
    'Under eventual consistency replicas may briefly disagree but converge once writes stop. It buys availability and low latency at the cost of reading stale data. CRDTs and last-write-wins are common ways to resolve the conflicting updates.',
    'Distributed Systems', ['consistency', 'replication'], 2019],
  ['ds-2pc', 'Two-phase commit',
    'Two-phase commit coordinates an atomic transaction across several nodes: a coordinator asks every participant to prepare, then tells all to commit or abort. It is blocking — if the coordinator fails after prepare, participants are stuck holding locks.',
    'Distributed Systems', ['transactions', 'atomicity'], 2017],
  ['ds-vector-clocks', 'Vector clocks',
    'A vector clock tracks one counter per node, so two events can be compared to see whether one happened before the other or whether they are concurrent. Concurrent updates surface as conflicts the application must resolve.',
    'Distributed Systems', ['causality', 'ordering'], 2018],
  ['ds-leader-election', 'Leader election',
    'Leader election picks a single node to coordinate work — sequencing writes, running schedulers. It usually rides on a consensus protocol or a lease in a coordination service, and must guarantee that two nodes never believe they are leader at once.',
    'Distributed Systems', ['coordination', 'consensus'], 2020],
  ['ds-saga', 'The saga pattern',
    'A saga implements a long-running business transaction as a sequence of local transactions, each with a compensating action that undoes it. It trades atomicity for availability across services and is the usual alternative to a distributed two-phase commit.',
    'Distributed Systems', ['transactions', 'microservices'], 2022],
  ['ds-quorum', 'Quorums',
    'Quorum systems require reads and writes to touch overlapping subsets of replicas. When the read set and write set always intersect — typically R + W greater than N — a read is guaranteed to see the latest write.',
    'Distributed Systems', ['replication', 'consistency'], 2019],
  ['ds-clock-skew', 'Clock skew',
    'Physical clocks on different machines drift apart, so wall-clock timestamps cannot reliably order events across nodes. Logical clocks, hybrid logical clocks and bounded-uncertainty schemes such as TrueTime exist precisely to work around this.',
    'Distributed Systems', ['time', 'ordering'], 2021],
  ['ds-circuit-breaker', 'Circuit breakers',
    'A circuit breaker stops calling a failing dependency. After a threshold of errors it trips open and fails fast, then periodically lets a trial request through to test recovery. It prevents one slow service from exhausting every caller\'s threads.',
    'Distributed Systems', ['reliability', 'resilience'], 2020],
  ['ds-message-queue', 'Message queues',
    'A message queue decouples producers from consumers, absorbs bursts and enables retries. Delivery is usually at-least-once, so consumers must be idempotent. Ordering, exactly-once and dead-letter handling are the details that decide whether a design actually works.',
    'Distributed Systems', ['messaging', 'async', 'reliability'], 2022],

  // ── Web ──────────────────────────────────────────────────
  ['web-http2', 'HTTP/2 multiplexing',
    'HTTP/2 carries many concurrent streams over a single TCP connection, ending the head-of-line blocking that forced HTTP/1.1 to open six connections per host. It also adds header compression and server push, though push saw little real-world use.',
    'Web', ['http', 'performance', 'networking'], 2017],
  ['web-quic', 'HTTP/3 and QUIC',
    'HTTP/3 runs over QUIC, a transport built on UDP. By moving streams below the transport layer it removes TCP\'s connection-level head-of-line blocking, and a connection survives an IP change so mobile clients keep their session across networks.',
    'Web', ['http', 'quic', 'networking'], 2022],
  ['web-cors', 'CORS',
    'Cross-Origin Resource Sharing lets a server opt into requests from other origins. The browser sends an Origin header and, for non-simple requests, a preflight OPTIONS call; the server answers with Access-Control-Allow headers that the browser enforces.',
    'Web', ['browser', 'security', 'http'], 2019],
  ['web-websockets', 'WebSockets',
    'WebSockets upgrade an HTTP connection to a persistent, bidirectional channel. They suit chat, multiplayer and live trading, but unlike plain HTTP they need their own reconnection, heartbeat and backpressure handling.',
    'Web', ['realtime', 'networking'], 2018],
  ['web-sse', 'Server-Sent Events',
    'Server-Sent Events stream text from server to client over a single long-lived HTTP response. They are one-directional and simpler than WebSockets, with automatic reconnection built in — a natural fit for live feeds and token-by-token LLM output.',
    'Web', ['realtime', 'streaming', 'http'], 2021],
  ['web-http-caching', 'HTTP caching',
    'HTTP caching is governed by Cache-Control, ETag and Last-Modified. Fresh responses are served without a network trip; stale ones are revalidated with a conditional request that may return 304 Not Modified. Getting the headers right is the cheapest performance win available.',
    'Web', ['http', 'performance', 'caching'], 2020],
  ['web-cdn', 'Content delivery networks',
    'A CDN serves content from edge locations near users, cutting latency and shielding the origin. Static assets cache for a long time behind hashed filenames; dynamic content uses short TTLs, stale-while-revalidate, or edge compute.',
    'Web', ['performance', 'edge', 'caching'], 2021],
  ['web-cookies', 'Cookies and SameSite',
    'Cookies carry state across requests. The Secure, HttpOnly and SameSite attributes harden them: HttpOnly hides a cookie from JavaScript, and SameSite controls whether it rides along on cross-site requests, which is the main defence against CSRF.',
    'Web', ['browser', 'security', 'sessions'], 2020],
  ['web-service-worker', 'Service workers',
    'A service worker is a background script that intercepts a site\'s network requests. It enables offline support, fine-grained caching strategies and push notifications, and is the engine behind installable progressive web apps.',
    'Web', ['browser', 'offline', 'pwa'], 2019],
  ['web-core-web-vitals', 'Core Web Vitals',
    'Core Web Vitals quantify user experience: Largest Contentful Paint for loading, Interaction to Next Paint for responsiveness, and Cumulative Layout Shift for visual stability. Field data from real users matters more than lab numbers.',
    'Web', ['performance', 'frontend', 'metrics'], 2023],
  ['web-hydration', 'Hydration',
    'Hydration attaches client-side JavaScript and event listeners to server-rendered HTML. It is costly on large pages, so frameworks now ship partial, progressive, selective and resumable hydration to avoid re-doing the server\'s work on the client.',
    'Web', ['frontend', 'rendering', 'performance'], 2023],
  ['web-edge-rendering', 'Edge rendering',
    'Edge rendering executes server code in CDN points of presence close to users. It cuts time-to-first-byte for dynamic pages but runs in a constrained runtime with tight CPU and memory budgets and no long-lived connections.',
    'Web', ['edge', 'rendering', 'performance'], 2023],
  ['web-rest', 'REST API design',
    'REST models an API as resources addressed by URLs and manipulated with HTTP verbs and status codes. Statelessness, consistent naming, pagination and proper cache headers are what make a REST API predictable and scalable.',
    'Web', ['api', 'http', 'design'], 2018],
  ['web-streaming', 'Streaming responses',
    'A streaming response sends the body in chunks as it is produced instead of buffering it whole. It lowers time-to-first-byte and memory use, and is how large exports and incremental LLM output reach the client without a long wait.',
    'Web', ['http', 'streaming', 'performance'], 2024],

  // ── Machine Learning ─────────────────────────────────────
  ['ml-embeddings', 'Text embeddings',
    'An embedding maps text to a dense vector so that semantically similar text lands nearby. Models such as OpenAI\'s text-embedding-3 produce these vectors; storing and searching them is what powers semantic search and retrieval-augmented generation.',
    'Machine Learning', ['embeddings', 'nlp', 'vectors'], 2024],
  ['ml-cosine', 'Cosine similarity',
    'Cosine similarity measures the angle between two vectors, ignoring their magnitude. For normalised embeddings it is equivalent to the dot product, which is why vector databases optimise that operation so heavily.',
    'Machine Learning', ['vectors', 'similarity', 'math'], 2021],
  ['ml-transformers', 'Transformers',
    'The transformer architecture processes a whole sequence in parallel using stacked self-attention and feed-forward layers. Dropping recurrence is what let language models scale to billions of parameters trained on enormous corpora.',
    'Machine Learning', ['transformers', 'architecture', 'nlp'], 2020],
  ['ml-attention', 'Attention',
    'Attention lets each token weigh every other token by relevance, computed from query, key and value projections. Self-attention is the transformer\'s core; its quadratic cost in sequence length is the main pressure behind long-context research.',
    'Machine Learning', ['transformers', 'attention'], 2021],
  ['ml-rag', 'Retrieval-augmented generation',
    'RAG grounds a language model in retrieved documents instead of relying only on its weights. A retriever finds relevant chunks, they are placed in the prompt, and the model answers from them — which cuts hallucination and keeps knowledge fresh.',
    'Machine Learning', ['rag', 'retrieval', 'llm'], 2024],
  ['ml-reranking', 'Reranking',
    'A reranker re-scores an initial candidate set with a heavier cross-encoder that reads the query and each document together. First-stage retrieval favours recall and speed; the reranker restores precision on the few results that will actually be used.',
    'Machine Learning', ['retrieval', 'ranking'], 2024],
  ['ml-chunking', 'Document chunking',
    'Chunking splits documents into passages small enough to embed and retrieve precisely. Chunk size, overlap and whether splits respect sentence or section boundaries strongly affect retrieval quality — often more than the choice of embedding model.',
    'Machine Learning', ['rag', 'retrieval', 'preprocessing'], 2024],
  ['ml-tokenization', 'Tokenization',
    'Tokenizers break text into sub-word units a model can process. Byte-pair encoding balances vocabulary size against sequence length. Token counts drive both context limits and API cost, so they matter well beyond the model internals.',
    'Machine Learning', ['nlp', 'preprocessing'], 2022],
  ['ml-finetuning', 'Fine-tuning',
    'Fine-tuning adapts a pretrained model to a task with further training on a smaller dataset. Parameter-efficient methods such as LoRA train only small adapter matrices, capturing most of the benefit at a fraction of the compute and storage.',
    'Machine Learning', ['training', 'llm'], 2023],
  ['ml-model-quantization', 'Model quantization',
    'Quantizing a model stores its weights at lower precision — int8 or int4 instead of 16-bit floats. It shrinks memory and speeds inference enough to run capable models on commodity hardware, with a modest and usually acceptable quality cost.',
    'Machine Learning', ['inference', 'optimization'], 2024],
  ['ml-gradient-descent', 'Gradient descent',
    'Gradient descent trains a model by repeatedly nudging its parameters down the loss gradient. Stochastic mini-batches make each step cheap and noisy; the learning rate is the single most important knob to get right.',
    'Machine Learning', ['training', 'optimization', 'math'], 2019],
  ['ml-overfitting', 'Overfitting and regularization',
    'A model overfits when it memorises training noise and fails to generalise. Regularization — weight decay, dropout, early stopping, more data — constrains the model so it learns the signal rather than the sample.',
    'Machine Learning', ['training', 'generalization'], 2018],
  ['ml-knn', 'k-nearest neighbours',
    'k-nearest neighbours classifies or retrieves a point by looking at its closest examples under some distance metric. It needs no training, but an exact search is linear in the dataset — which is exactly why approximate vector indexes exist.',
    'Machine Learning', ['algorithms', 'retrieval'], 2017],
  ['ml-semantic-search', 'Semantic search',
    'Semantic search matches meaning rather than keywords by comparing query and document embeddings. It finds paraphrases that lexical search misses, but can drift off exact terms — which is why hybrid search pairs it with keyword matching.',
    'Machine Learning', ['search', 'embeddings', 'retrieval'], 2024],

  // ── Security ─────────────────────────────────────────────
  ['sec-jwt', 'JSON Web Tokens',
    'A JWT is a signed, base64url-encoded set of claims. The signature lets a server trust the token without a database lookup, which is convenient but means a token cannot be revoked before it expires — so keep lifetimes short.',
    'Security', ['auth', 'tokens'], 2020],
  ['sec-oauth', 'OAuth 2.0',
    'OAuth 2.0 lets a user grant an application limited access to their account without sharing a password. The authorization-code flow with PKCE is the current recommendation for web and native apps; implicit flow is deprecated.',
    'Security', ['auth', 'oauth', 'identity'], 2021],
  ['sec-tls', 'The TLS handshake',
    'A TLS handshake authenticates the server with a certificate and negotiates session keys. TLS 1.3 cut the handshake to one round trip, and a resumed session can send data on the first message, so encryption costs almost nothing.',
    'Security', ['tls', 'encryption', 'networking'], 2019],
  ['sec-csp', 'Content Security Policy',
    'A Content Security Policy tells the browser which sources of scripts, styles and other content to trust. A strict policy is the strongest mitigation for cross-site scripting, since injected inline scripts simply will not run.',
    'Security', ['browser', 'xss', 'headers'], 2021],
  ['sec-sql-injection', 'SQL injection',
    'SQL injection happens when user input is concatenated into a query and is interpreted as code. Parameterized queries — sending SQL and data on separate channels — eliminate the class entirely; escaping by hand does not.',
    'Security', ['injection', 'database', 'owasp'], 2018],
  ['sec-xss', 'Cross-site scripting',
    'Cross-site scripting injects attacker JavaScript into a page so it runs with the victim\'s session. Contextual output encoding, treating all input as untrusted, and a strict Content Security Policy are the layered defences against it.',
    'Security', ['xss', 'browser', 'owasp'], 2019],
  ['sec-csrf', 'Cross-site request forgery',
    'CSRF tricks a logged-in user\'s browser into sending an unwanted authenticated request. SameSite cookies block most of it; anti-CSRF tokens and checking the Origin header cover the rest.',
    'Security', ['csrf', 'browser', 'owasp'], 2019],
  ['sec-hashing', 'Password hashing',
    'Passwords must be stored as salted hashes from a slow, memory-hard function — bcrypt, scrypt or Argon2 — never as plaintext or a fast hash. The deliberate cost is what makes a stolen database expensive to crack.',
    'Security', ['auth', 'hashing', 'passwords'], 2020],
  ['sec-rate-limiting', 'Rate limiting',
    'Rate limiting caps how often a client may act, protecting against abuse, brute force and runaway cost. Token bucket allows bursts up to a ceiling; sliding-window and GCRA give smoother enforcement.',
    'Security', ['abuse', 'api', 'throttling'], 2022],
  ['sec-secrets', 'Secrets management',
    'Secrets — keys, tokens, passwords — must stay out of source control and reach code through environment variables or a secrets manager. Short-lived, rotatable credentials limit the blast radius when one inevitably leaks.',
    'Security', ['secrets', 'ops'], 2022],
  ['sec-least-privilege', 'Least privilege',
    'The principle of least privilege grants every user, service and token only the access it needs and no more. It shrinks the blast radius of a compromise and is the reason scoped, short-lived credentials beat broad standing ones.',
    'Security', ['access-control', 'principles'], 2021],
  ['sec-mfa', 'Multi-factor authentication',
    'Multi-factor authentication requires evidence from more than one category — something you know, have or are. It defeats stolen passwords; phishing-resistant factors such as passkeys and hardware keys also defeat the fake login pages that beat one-time codes.',
    'Security', ['auth', 'mfa', 'identity'], 2023],
  ['sec-rbac', 'Role-based access control',
    'Role-based access control assigns permissions to roles and roles to users, so access is managed in a few well-understood buckets rather than per user. Attribute-based access control generalises it to policies over user, resource and context attributes.',
    'Security', ['access-control', 'authorization'], 2020],
  ['sec-zero-trust', 'Zero trust',
    'Zero trust drops the assumption that the internal network is safe. Every request is authenticated, authorised and encrypted on its own merits, regardless of origin — so a breached perimeter no longer means free movement inside.',
    'Security', ['architecture', 'network', 'principles'], 2022],

  // ── Systems ──────────────────────────────────────────────
  ['sys-caching', 'Caching strategies',
    'A cache trades freshness for speed. Cache-aside, read-through and write-through differ in who populates the cache and when. The hard parts are always invalidation and the thundering herd when a hot key expires.',
    'Systems', ['caching', 'performance'], 2021],
  ['sys-load-balancing', 'Load balancing',
    'A load balancer spreads traffic over many backends. Round-robin is simple; least-connections and latency-aware policies handle uneven work better. Health checks remove dead backends, and sticky sessions trade balance for cache locality.',
    'Systems', ['scaling', 'networking', 'availability'], 2020],
  ['sys-observability', 'Observability',
    'Observability is the ability to ask new questions of a running system from its outputs. Its three pillars — metrics, logs and traces — answer how much, what happened, and where the time went, respectively.',
    'Systems', ['monitoring', 'ops'], 2022],
  ['sys-tracing', 'Distributed tracing',
    'Distributed tracing follows one request across services as a tree of timed spans linked by a propagated trace id. It is the only practical way to find which hop in a chain of microservices is spending the latency.',
    'Systems', ['observability', 'microservices'], 2023],
  ['sys-containers', 'Containers',
    'A container packages an application with its dependencies and runs it as an isolated process using kernel namespaces and cgroups. It starts in milliseconds and shares the host kernel, making it far lighter than a virtual machine.',
    'Systems', ['containers', 'deployment'], 2019],
  ['sys-orchestration', 'Container orchestration',
    'An orchestrator such as Kubernetes schedules containers across a cluster, restarts failures, scales replicas and handles rollouts. You declare the desired state and a control loop continuously reconciles reality toward it.',
    'Systems', ['kubernetes', 'deployment', 'scaling'], 2021],
  ['sys-iac', 'Infrastructure as code',
    'Infrastructure as code defines servers, networks and services in version-controlled files instead of console clicks. Tools diff the declared state against reality and converge it, making environments reproducible and reviewable.',
    'Systems', ['iac', 'devops', 'automation'], 2022],
  ['sys-cicd', 'CI/CD pipelines',
    'Continuous integration builds and tests every change; continuous delivery keeps it always shippable. A good pipeline gives fast feedback, runs the same way locally and in CI, and makes a deploy a routine, low-drama event.',
    'Systems', ['devops', 'automation', 'deployment'], 2021],
  ['sys-blue-green', 'Blue-green and canary deploys',
    'Blue-green keeps two production environments and flips traffic between them for instant rollback. Canary releases a change to a small slice of traffic first and watches the metrics before widening it.',
    'Systems', ['deployment', 'release', 'devops'], 2020],
  ['sys-autoscaling', 'Autoscaling',
    'Autoscaling adjusts capacity to demand — horizontally by adding instances, vertically by resizing them. Good signals and sane cooldowns matter; scaling on a lagging metric causes oscillation, and cold starts blunt how fast it can react.',
    'Systems', ['scaling', 'cloud', 'ops'], 2022],
  ['sys-gc', 'Garbage collection',
    'Garbage collection reclaims memory no longer reachable by the program. Generational collectors exploit the fact that most objects die young; the perennial tension is throughput versus pause time.',
    'Systems', ['memory', 'runtime', 'performance'], 2018],
  ['sys-concurrency', 'Threads versus async',
    'Threads let the OS preempt blocking code but cost memory and context switches. Async uses an event loop and non-blocking I/O to handle many connections cheaply, at the price of code that must never block the loop.',
    'Systems', ['concurrency', 'performance', 'runtime'], 2021],
  ['sys-memory-hierarchy', 'The memory hierarchy',
    'Registers, CPU caches, main memory and disk each get larger and far slower. Performance often comes down to locality — keeping hot data in cache — because a cache miss to main memory costs hundreds of cycles.',
    'Systems', ['hardware', 'performance'], 2017],
  ['sys-profiling', 'Profiling',
    'A profiler shows where a program actually spends time or memory, as opposed to where you guess it does. Measuring before optimising is the discipline that stops effort going into code that was never the bottleneck.',
    'Systems', ['performance', 'tooling'], 2019],
];

export function corpus(): Doc[] {
  return ROWS.map(([id, title, content, category, tags, year]) => ({
    id,
    title,
    content,
    category,
    tags,
    source: 'knowledge-base',
    year,
  }));
}
